---
- name: stop etcd
  service: 
    name: etcd
    state: stopped 
    enabled: no
  ignore_errors: true

- name: remove etcd group
  group:
    name: etcd
    state: absent

- name: remove etcd user
  user:
    name: etcd
    state: absent

- name: remove etcd directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/bin/etcd
    - /usr/bin/etcdctl
    - /tmp/etcd-{{ etcd_version }}-linux-amd64
    - /tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    - /tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz.MD5
    - /opt/etcd
    - /lib/systemd/system/etcd.service
    - /etc/etcd.conf
