---
- name: stop px-lighthouse
  service: 
    name: px-lighthouse
    state: stopped
    enabled: no
  ignore_errors: true

- name: clear px-lighthouse
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/px-lighthouse.service
    - /opt/px-lighthouse

- name: systemd daemon-reload
  systemd:
    daemon-reload: yes
