---
- name: is px-enterprise version {{ portworx_enterprise_version }} ?
  shell: /opt/pwx/bin/pxctl --version|grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+'
  register: version_res

- name: sync px-runc
  shell: > 
         docker run 
         --entrypoint /runc-entry-point.sh
         --rm 
         --privileged=true
         -v /opt/pwx:/opt/pwx
         -v /etc/pwx:/etc/pwx
         {{ hub_offline_prefix }}/px-enterprise:{{ portworx_enterprise_version }}
         --upgrade
  when: version_res.stdout != portworx_enterprise_version
  notify: restart portworx
