---
- name: stop portworx
  service: 
    name: portworx
    state: stopped
    enabled: no
  ignore_errors: true

- name: filter mount point
  shell: df | awk 'NR>1{print $NF}' | sort -r |grep -E -v '^/sys/fs/cgroup$|^/run$|^/dev$|^/$'
  register: df_result
  ignore_errors: true

- set_fact: DF_RESULT={{ df_result.stdout.split() }}
- name: unmount
  mount:
    path: "{{ item }}"
    state: unmounted
  with_items: "{{ DF_RESULT }}"
  ignore_errors: true

- name: clear portworx
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/portworx.service
    - /etc/systemd/system/portworx-reboot.service
    - /opt/pwx
  ignore_errors: true

- name: systemd daemon-reload
  systemd:
    daemon-reload: yes
