---
- name: stop chrony
  service: 
    name: chronyd
    state: stopped 
    enabled: no
  ignore_errors: true

- name: uninstall chrony
  yum:
    name: chrony
    state: absent

- name: remove chrony user
  user:
    name: chrony
    state: absent

- name: clear 
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/yum.repos.d/dce_offline.repo
    - /etc/yum.repos.d/centos7_base_repo.repo
