- include_tasks: offline_yum_repo.yml
- name: yum.conf skip_broken=1, obsoletes=0
  ini_file:
    path: /etc/yum.conf
    section: main
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: True
  with_items:
    - { option: skip_broken, value: 1 }
    - { option: obsoletes, value: 0 }

- name: install docker-ce-{{ docker_version }}
  yum: 
    name: "{{ item }}"
    state: present
    disablerepo: "*"
    enablerepo: dce_offline
    update_cache: yes
  with_items:
    - docker-ce-{{ docker_version }}

- name: yum.conf skip_broken=0, obsoletes=1
  ini_file:
    path: /etc/yum.conf
    section: main
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: True
  with_items:
    - { option: skip_broken, value: 0 }
    - { option: obsoletes, value: 1 }

- name: tune docker.service
  ini_file:
    path: /lib/systemd/system/docker.service
    section: Service
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: Restart, value: on-failure }
    - { option: RestartSec, value: 3 }

- name: create docker configuration directory(/etc/docker)
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0700

- name: sync daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: systemd daemon-reload
  systemd:
    daemon-reload: yes

- name: start docker
  service: 
    name: docker
    state: started 
    enabled: yes
