- name: yum.conf obsoletes=0
  ini_file:
    path: /etc/yum.conf
    section: main
    option: obsoletes
    value: 0

- name: install docker-ce-{{ docker_version }}
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-ce-{{ docker_version }}

- name: yum.conf obsoletes=1
  ini_file:
    path: /etc/yum.conf
    section: main
    option: obsoletes
    value: 1

- name: tune docker.service
  ini_file:
    path: /lib/systemd/system/docker.service
    section: Service
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: Restart, value: on-failure }
    - { option: RestartSec, value: 3 }

- name: systemd daemon-reload
  systemd:
    daemon-reload: yes

- name: start docker
  service: 
    name: docker
    state: started 
    enabled: yes
