---
- name: stop docker daemon
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - docker
    - chronyd
  ignore_errors: true

- name: uninstall docker-ce-{{ docker_version }}
  yum: 
    name: "{{ item }}"
    state: absent
  with_items:
    - docker-ce-{{ docker_version }}
    - chrony

- name: remove chrony user
  user:
    name: chrony
    state: absent

- name: filter mount point
  shell: df | awk 'NR>1{print $NF}' | sort -r
  register: df_result

- set_fact: DF_RESULT={{ df_result.stdout.split() }}
- name: unmount
  mount:
    path: "{{ item }}"
    state: unmounted
  with_items: "{{ DF_RESULT }}"
  ignore_errors: true

- name: clear docker left directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/docker
    - /var/lib/dockershim
    - /var/lib/docker
    - /var/lib/docker
    - /etc/chrony.conf
    - /etc/yum.repos.d/dce_offline.repo
    - /etc/yum.repos.d/centos7_base_repo.repo
