---
- name: stop docker daemon
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - docker
  ignore_errors: true

- name: remove repos
  file:
    path: /etc/yum.repos.d/{{ item }}
    state: absent
  with_items:
    - docker-ce.repo
    - docker_offline.repo

- name: uninstall docker-ce-{{ docker_version }}
  yum: 
    name: "{{ item }}"
    state: absent
  with_items:
    - docker-ce-{{ docker_version }}

- name: filter mounted container dirs
  shell: df
  register: df_result

- set_fact: DF_RESULT={{ df_result.stdout | regex_findall('(/var/lib/kubelet/pods/.+)') }}
- name: unmount left pods 
  mount:
    path: "{{ item }}"
    state: unmounted
  with_items: "{{ DF_RESULT }}"

- name: clear docker left directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/docker
    - /var/lib/dockershim
    - /var/lib/docker

- name: thinpool
  lvol:
    vg: "{{ VG_NAME }}"
    lv: "{{ THINPOOL_NAME }}"
    state: absent
    force: "{{ force_remove | default('no') }}"
  ignore_errors: true
  tags: thinpool_remove

- name: vg
  lvg:
    vg: "{{ VG_NAME }}"
    state: absent
    force: "{{ force_remove | default('no') }}"
  ignore_errors: true
  tags: vg_remove
