---
- name: install chrony
  yum: 
    name: chrony
    state: present

- name: configure chrony 
  template: 
    src: chrony.conf.j2 
    dest: /etc/chrony.conf
  notify: restart chrony

- name: start the chrony service
  service: 
    name: chronyd 
    state: started 
    enabled: yes
